### ISSUE TITLE
Does not work with Asciidoctorj 2.x

### ISSUE THREAD

**Issue by aalmiray** [bmuschko/asciidoctorj-tabbed-code-extension#1]
It looks like `org.asciidoctor.extension.spi.ExtensionRegistry` has been relocated to `org.asciidoctor.jruby.extension.spi.ExtensionRegistry` in Asciidoctorj 2.x. This makes version `0.2` of this extension miss the required hook to perform its work.

**Comment by bmuschko** [comment]
Thanks for the PR. Is there any functional change that drives the need for upgrading the plugin?

**Comment by aalmiray** [comment]
I've been publishing http://kordamp.org/kordamp-gradle-plugins/ for a while and noticed that the extension was not being applied at all. Turns out the extension was never picked due to the compatibility break in Asciidoctorj 2.x

**Comment by bmuschko** [comment]
I am still not quite clear what you did in your project that caused the issue. Is it because you applied the `org.asciidoctor.gradle.AsciidoctorPlugin` and set `org.asciidoctor.gradle.AsciidoctorExtension.version = '2.2.0'`? It somewhat surprising that the processing code of the `AsciidoctorPlugin` doesn't fail but rather swallows the issue.

Not sure if you saw the note in the documentation of this project?

> This extension is based on AsciidoctorJ version 1.6.0-RC1. Make sure that the consuming project uses that exact version to avoid incompatibilities. The alpha versions 1.6.0 of AsciidoctorJ are not compatible.

And then to that extend, why do you want to upgrade to a newer Asciidoctorj version? Is just "because I want to upgrade to a new version" or are there functional, end user changes you'd like to consume?

**Comment by aalmiray** [comment]
Yes, I’ve seen the note about 1.6.0. The thing is, asciidoctor-gradle-plugin 3.x relies on asciidoctorj 2.x, and those are the versions I’m currently using.

**Comment by bmuschko** [comment]
Has been released...
